### ISSUE TITLE
Formspree is phasing out legacy forms

### ISSUE THREAD

**Issue by tmaier** [StartBootstrap/startbootstrap-clean-blog-jekyll#257]
I just received an email from formspree:
![image](https://user-images.githubusercontent.com/350038/106513708-970caf00-64d3-11eb-9113-ab1d9344995e.png)

Formspree is phasing out support for legacy forms. See https://help.formspree.io/hc/en-us/articles/360056076314

Thus, the URI to submit the form must be reworked. Maybe the JavaScript is also obsolete due to this change...

**Comment by tmaier** [comment]
#248 could be a possible fix

**Comment by davidtmiller** [comment]
I am going to be going a different direction with the forms, and since there are so many static options out there as of now I am going to leave the forms up to the developer for the time being. I will be removing Formspree and replacing with a new service or something that we build! Sorry for the delay here.

**Comment by mjunaid** [comment]
Hello there, thank you so much for your theme. I am wondering if there has been update on Formspree/new service for contact?
